import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "./components/NavBar";
import { StoreProvider } from "./CartContext";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import Footer from "./components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "EchoEstates",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-slate-50`}>
        <StoreProvider>
          <NavBar />
          <hr className="mx-6 mt-2 mb-2 flex justify-between lg:mx-10 lg:mt-4 text-black" />
          {children}
          <ToastContainer
            position="bottom-left"
            autoClose={1500}
            hideProgressBar={false}
            newestOnTop={false}
            closeOnClick
            rtl={false}
            pauseOnFocusLoss
            draggable
            pauseOnHover
            theme="colored"
          />
          <hr className="mx-6 mt-2 mb-2 flex justify-between lg:mx-10 lg:mt-4 text-black" />
          <Footer />
        </StoreProvider>
      </body>
    </html>
  );
}
